# Site settings
title: "Securing the Digital Frontier"
description: "Senior Security Engineer | 8+ Years DevSecOps, SRE & Cloud Security"
author: "Varun Bhandari"
email: your.email@example.com
url: "https://z-varun.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Permalink structure for blog posts
permalink: /blog/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Social links
github_username: z-varun
linkedin_username: varun-bhandari5

# Site navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/
