[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.1.0"

# HTTPS Redirects
[[redirects]]
  from = "http://cswithvarun.com/*"
  to = "https://cswithvarun.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://z-varun.netlify.app/*"
  to = "https://cswithvarun.com/:splat"
  status = 301
  force = true

# STRICT SECURITY HEADERS (No unsafe-inline, no unsafe-eval)
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    
    # Perfect CSP - No unsafe directives
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://cdnjs.cloudflare.com;
      style-src 'self' https://cdnjs.cloudflare.com https://fonts.googleapis.com;
      font-src 'self' https://cdnjs.cloudflare.com https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self';
      frame-ancestors 'self';
      base-uri 'self';
      form-action 'self';
      upgrade-insecure-requests;
    """
    
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=()"

# Cache Control
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
